name: minerva_controller
description: Required to use controllers to configure the Minerva server.
version: 1.0.0
homepage: https://github.com/GlebBatykov/minerva_controller

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  minerva: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
